<a href="https://colab.research.google.com/github/navya-goel28/deeplearning-using-pytorch/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(nn.Linear(num_features, 3),
                                 nn.ReLU(),
                                 nn.Linear(3, 1),
                                 nn.Sigmoid())
  #  self.linear1 = nn.Linear(num_features, 3)
  #  self.relu = nn.ReLU()
  #  self.linear2 = nn.Linear(3, 1)
  #  self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.network(features)

 #   out = self.relu(out)
 #   out = self.linear2(out)
 #   out = self.sigmoid(out)

    return out


In [13]:
features = torch.rand(10, 5)
model = Model(features.shape[1])
model(features)

tensor([[0.4317],
        [0.4190],
        [0.3858],
        [0.4091],
        [0.3921],
        [0.3922],
        [0.3981],
        [0.4115],
        [0.3721],
        [0.4095]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3582, -0.2577,  0.0957, -0.0073, -0.3310],
        [ 0.1223, -0.3552, -0.0008,  0.2263,  0.3744],
        [ 0.4420,  0.1592, -0.2507, -0.3904,  0.2994]], requires_grad=True)

In [7]:
model.linear2.bias

Parameter containing:
tensor([-0.3772], requires_grad=True)

In [10]:
!pip install torchinfo

In [11]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00